### ISSUE TITLE
MythicMobs drop from mobs doesnt work

### ISSUE THREAD

**Issue by Retside** [YKDZ/DailyShop#3]
When using MythicMobs 5.7.1, mob drops do not work. I’m not sure how this is possible, but when I remove DailyShop from my plugins folder, everything works normally. However, when the plugin is present, everything breaks. Aside from this issue, everything else works almost normally. It's a really good plugin.

To Reproduce
1. Add a custom drop to a mob, such as: exp 1000-1500 1
2. Kill the mob in-game.

- Server version: [1.21 Purpur]
- Plugin Version: [0.2.4]

**Comment by Retside** [comment]
Also, mobs sometimes spawn incorrectly, the boss bar is not displayed or something else

**Comment by Retside** [comment]
ok, nevermind i dont know how but it got fixed

**Comment by YKDZ** [comment]
> Okay, never mind, I don't know how, but it was fixed.好吧，没关系，我不知道怎么办，但它已经修复了。

I'm curious about this because DailyShop doesn't address MythicMobs handling of drops. Please submit new Issues in GitHub if there is a new status to follow.

**Comment by Retside** [comment]
I was also wondering how this happens, but when I deleted one of the default configurations, + KingSword from products, everything was fixed

**Comment by YKDZ** [comment]
I think I fixed the bug and you can download the new version to test it.
